/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 glitch.glb 
Author: Tycho Magnetic Anomaly (https://sketchfab.com/Tycho_Magnetic_Anomaly)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/isomatrix-glitch-b35a90b8b302465999507cbde367e704
Title: Isomatrix Glitch
*/

"use client"

import React, { useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Glitch(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF("/models/glitch/glitch.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions) {
      Object.values(actions).forEach((action) => {
        action.reset().fadeIn(.5).play();
      });
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.231}
        >
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="Plane_0"
                position={[1, 5, 0]}
                rotation={[0, 0, Math.PI]}
              >
                <mesh
                  name="Object_4"
                  geometry={nodes.Object_4.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane001_1" position={[-1, 5, 0]}>
                <mesh
                  name="Object_6"
                  geometry={nodes.Object_6.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane002_2" position={[-2, 5, -1]}>
                <mesh
                  name="Object_8"
                  geometry={nodes.Object_8.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane003_3" position={[1, 5, 2]}>
                <mesh
                  name="Object_10"
                  geometry={nodes.Object_10.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane004_4" position={[2, 5, -1]}>
                <mesh
                  name="Object_12"
                  geometry={nodes.Object_12.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane005_5" position={[-1, 5, -2]}>
                <mesh
                  name="Object_14"
                  geometry={nodes.Object_14.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane006_6" position={[-1, 5, 2]}>
                <mesh
                  name="Object_16"
                  geometry={nodes.Object_16.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane007_7" position={[2, 5, 1]}>
                <mesh
                  name="Object_18"
                  geometry={nodes.Object_18.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane008_8" position={[1, 5, -2]}>
                <mesh
                  name="Object_20"
                  geometry={nodes.Object_20.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane009_9" position={[-3, 5, 2]}>
                <mesh
                  name="Object_22"
                  geometry={nodes.Object_22.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane010_10" position={[-4, 5, 1]}>
                <mesh
                  name="Object_24"
                  geometry={nodes.Object_24.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane011_11" position={[-4, 5, -1]}>
                <mesh
                  name="Object_26"
                  geometry={nodes.Object_26.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane012_12" position={[-4, 5, -3]}>
                <mesh
                  name="Object_28"
                  geometry={nodes.Object_28.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane013_13" position={[-1, 5, -4]}>
                <mesh
                  name="Object_30"
                  geometry={nodes.Object_30.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane014_14" position={[-3, 5, -4]}>
                <mesh
                  name="Object_32"
                  geometry={nodes.Object_32.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane015_15" position={[1, 5, -4]}>
                <mesh
                  name="Object_34"
                  geometry={nodes.Object_34.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane016_16" position={[3, 5, -4]}>
                <mesh
                  name="Object_36"
                  geometry={nodes.Object_36.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane017_17" position={[4, 5, -3]}>
                <mesh
                  name="Object_38"
                  geometry={nodes.Object_38.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane018_18" position={[4, 5, -1]}>
                <mesh
                  name="Object_40"
                  geometry={nodes.Object_40.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane019_19" position={[4, 5, 1]}>
                <mesh
                  name="Object_42"
                  geometry={nodes.Object_42.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane020_20" position={[4, 5, 3]}>
                <mesh
                  name="Object_44"
                  geometry={nodes.Object_44.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane021_21" position={[3, 5, 4]}>
                <mesh
                  name="Object_46"
                  geometry={nodes.Object_46.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane022_22" position={[1, 5, 4]}>
                <mesh
                  name="Object_48"
                  geometry={nodes.Object_48.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane023_23" position={[-1, 5, 4]}>
                <mesh
                  name="Object_50"
                  geometry={nodes.Object_50.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane024_24" position={[-3, 5, 4]}>
                <mesh
                  name="Object_52"
                  geometry={nodes.Object_52.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Plane025_53"
                position={[-5, 1, 0]}
                rotation={[0, 0, Math.PI]}
              >
                <mesh
                  name="Object_54"
                  geometry={nodes.Object_54.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane026_54" position={[-5, -1, 0]}>
                <mesh
                  name="Object_56"
                  geometry={nodes.Object_56.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane027_55" position={[-5, -2, -1]}>
                <mesh
                  name="Object_58"
                  geometry={nodes.Object_58.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane028_56" position={[-5, 1, 2]}>
                <mesh
                  name="Object_60"
                  geometry={nodes.Object_60.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane029_57" position={[-5, 2, -1]}>
                <mesh
                  name="Object_62"
                  geometry={nodes.Object_62.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane030_58" position={[-5, -1, -2]}>
                <mesh
                  name="Object_64"
                  geometry={nodes.Object_64.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane031_59" position={[-5, -1, 2]}>
                <mesh
                  name="Object_66"
                  geometry={nodes.Object_66.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane032_60" position={[-5, 2, 1]}>
                <mesh
                  name="Object_68"
                  geometry={nodes.Object_68.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane033_61" position={[-5, 1, -2]}>
                <mesh
                  name="Object_70"
                  geometry={nodes.Object_70.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane034_62" position={[-5, -3, 2]}>
                <mesh
                  name="Object_72"
                  geometry={nodes.Object_72.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane035_63" position={[-5, -4, 1]}>
                <mesh
                  name="Object_74"
                  geometry={nodes.Object_74.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane036_64" position={[-5, -4, -1]}>
                <mesh
                  name="Object_76"
                  geometry={nodes.Object_76.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane037_65" position={[-5, -4, -3]}>
                <mesh
                  name="Object_78"
                  geometry={nodes.Object_78.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane038_66" position={[-5, -1, -4]}>
                <mesh
                  name="Object_80"
                  geometry={nodes.Object_80.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane039_67" position={[-5, -3, -4]}>
                <mesh
                  name="Object_82"
                  geometry={nodes.Object_82.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane040_68" position={[-5, 1, -4]}>
                <mesh
                  name="Object_84"
                  geometry={nodes.Object_84.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane041_69" position={[-5, 3, -4]}>
                <mesh
                  name="Object_86"
                  geometry={nodes.Object_86.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane042_70" position={[-5, 4, -3]}>
                <mesh
                  name="Object_88"
                  geometry={nodes.Object_88.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane043_71" position={[-5, 4, -1]}>
                <mesh
                  name="Object_90"
                  geometry={nodes.Object_90.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane044_72" position={[-5, 4, 1]}>
                <mesh
                  name="Object_92"
                  geometry={nodes.Object_92.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane045_73" position={[-5, 4, 3]}>
                <mesh
                  name="Object_94"
                  geometry={nodes.Object_94.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane046_74" position={[-5, 3, 4]}>
                <mesh
                  name="Object_96"
                  geometry={nodes.Object_96.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane047_75" position={[-5, 1, 4]}>
                <mesh
                  name="Object_98"
                  geometry={nodes.Object_98.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane048_76" position={[-5, -1, 4]}>
                <mesh
                  name="Object_100"
                  geometry={nodes.Object_100.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane049_77" position={[-5, -3, 4]}>
                <mesh
                  name="Object_102"
                  geometry={nodes.Object_102.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Plane050_106"
                position={[-1, -5, 0]}
                rotation={[0, 0, Math.PI]}
              >
                <mesh
                  name="Object_104"
                  geometry={nodes.Object_104.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane051_107" position={[1, -5, 0]}>
                <mesh
                  name="Object_106"
                  geometry={nodes.Object_106.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane052_108" position={[2, -5, -1]}>
                <mesh
                  name="Object_108"
                  geometry={nodes.Object_108.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane053_109" position={[-1, -5, 2]}>
                <mesh
                  name="Object_110"
                  geometry={nodes.Object_110.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane054_110" position={[-2, -5, -1]}>
                <mesh
                  name="Object_112"
                  geometry={nodes.Object_112.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane055_111" position={[1, -5, -2]}>
                <mesh
                  name="Object_114"
                  geometry={nodes.Object_114.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane056_112" position={[1, -5, 2]}>
                <mesh
                  name="Object_116"
                  geometry={nodes.Object_116.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane057_113" position={[-2, -5, 1]}>
                <mesh
                  name="Object_118"
                  geometry={nodes.Object_118.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane058_114" position={[-1, -5, -2]}>
                <mesh
                  name="Object_120"
                  geometry={nodes.Object_120.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane059_115" position={[3, -5, 2]}>
                <mesh
                  name="Object_122"
                  geometry={nodes.Object_122.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane060_116" position={[4, -5, 1]}>
                <mesh
                  name="Object_124"
                  geometry={nodes.Object_124.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane061_117" position={[4, -5, -1]}>
                <mesh
                  name="Object_126"
                  geometry={nodes.Object_126.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane062_118" position={[4, -5, -3]}>
                <mesh
                  name="Object_128"
                  geometry={nodes.Object_128.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane063_119" position={[1, -5, -4]}>
                <mesh
                  name="Object_130"
                  geometry={nodes.Object_130.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane064_120" position={[3, -5, -4]}>
                <mesh
                  name="Object_132"
                  geometry={nodes.Object_132.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane065_121" position={[-1, -5, -4]}>
                <mesh
                  name="Object_134"
                  geometry={nodes.Object_134.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane066_122" position={[-3, -5, -4]}>
                <mesh
                  name="Object_136"
                  geometry={nodes.Object_136.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane067_123" position={[-4, -5, -3]}>
                <mesh
                  name="Object_138"
                  geometry={nodes.Object_138.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane068_124" position={[-4, -5, -1]}>
                <mesh
                  name="Object_140"
                  geometry={nodes.Object_140.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane069_125" position={[-4, -5, 1]}>
                <mesh
                  name="Object_142"
                  geometry={nodes.Object_142.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane070_126" position={[-4, -5, 3]}>
                <mesh
                  name="Object_144"
                  geometry={nodes.Object_144.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane071_127" position={[-3, -5, 4]}>
                <mesh
                  name="Object_146"
                  geometry={nodes.Object_146.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane072_128" position={[-1, -5, 4]}>
                <mesh
                  name="Object_148"
                  geometry={nodes.Object_148.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane073_129" position={[1, -5, 4]}>
                <mesh
                  name="Object_150"
                  geometry={nodes.Object_150.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane074_130" position={[3, -5, 4]}>
                <mesh
                  name="Object_152"
                  geometry={nodes.Object_152.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Plane075_159"
                position={[5, -1, 0]}
                rotation={[0, 0, Math.PI]}
              >
                <mesh
                  name="Object_154"
                  geometry={nodes.Object_154.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane076_160" position={[5, 1, 0]}>
                <mesh
                  name="Object_156"
                  geometry={nodes.Object_156.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane077_161" position={[5, 2, -1]}>
                <mesh
                  name="Object_158"
                  geometry={nodes.Object_158.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane078_162" position={[5, -1, 2]}>
                <mesh
                  name="Object_160"
                  geometry={nodes.Object_160.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane079_163" position={[5, -2, -1]}>
                <mesh
                  name="Object_162"
                  geometry={nodes.Object_162.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane080_164" position={[5, 1, -2]}>
                <mesh
                  name="Object_164"
                  geometry={nodes.Object_164.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane081_165" position={[5, 1, 2]}>
                <mesh
                  name="Object_166"
                  geometry={nodes.Object_166.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane082_166" position={[5, -2, 1]}>
                <mesh
                  name="Object_168"
                  geometry={nodes.Object_168.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane083_167" position={[5, -1, -2]}>
                <mesh
                  name="Object_170"
                  geometry={nodes.Object_170.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane084_168" position={[5, 3, 2]}>
                <mesh
                  name="Object_172"
                  geometry={nodes.Object_172.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane085_169" position={[5, 4, 1]}>
                <mesh
                  name="Object_174"
                  geometry={nodes.Object_174.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane086_170" position={[5, 4, -1]}>
                <mesh
                  name="Object_176"
                  geometry={nodes.Object_176.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane087_171" position={[5, 4, -3]}>
                <mesh
                  name="Object_178"
                  geometry={nodes.Object_178.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane088_172" position={[5, 1, -4]}>
                <mesh
                  name="Object_180"
                  geometry={nodes.Object_180.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane089_173" position={[5, 3, -4]}>
                <mesh
                  name="Object_182"
                  geometry={nodes.Object_182.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane090_174" position={[5, -1, -4]}>
                <mesh
                  name="Object_184"
                  geometry={nodes.Object_184.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane091_175" position={[5, -3, -4]}>
                <mesh
                  name="Object_186"
                  geometry={nodes.Object_186.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane092_176" position={[5, -4, -3]}>
                <mesh
                  name="Object_188"
                  geometry={nodes.Object_188.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane093_177" position={[5, -4, -1]}>
                <mesh
                  name="Object_190"
                  geometry={nodes.Object_190.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane094_178" position={[5, -4, 1]}>
                <mesh
                  name="Object_192"
                  geometry={nodes.Object_192.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane095_179" position={[5, -4, 3]}>
                <mesh
                  name="Object_194"
                  geometry={nodes.Object_194.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane096_180" position={[5, -3, 4]}>
                <mesh
                  name="Object_196"
                  geometry={nodes.Object_196.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane097_181" position={[5, -1, 4]}>
                <mesh
                  name="Object_198"
                  geometry={nodes.Object_198.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane098_182" position={[5, 1, 4]}>
                <mesh
                  name="Object_200"
                  geometry={nodes.Object_200.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane099_183" position={[5, 3, 4]}>
                <mesh
                  name="Object_202"
                  geometry={nodes.Object_202.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Plane100_212"
                position={[0, -1, -5]}
                rotation={[0, 0, Math.PI]}
              >
                <mesh
                  name="Object_204"
                  geometry={nodes.Object_204.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane101_213" position={[0, 1, -5]}>
                <mesh
                  name="Object_206"
                  geometry={nodes.Object_206.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane102_214" position={[-1, 2, -5]}>
                <mesh
                  name="Object_208"
                  geometry={nodes.Object_208.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane103_215" position={[2, -1, -5]}>
                <mesh
                  name="Object_210"
                  geometry={nodes.Object_210.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane104_216" position={[-1, -2, -5]}>
                <mesh
                  name="Object_212"
                  geometry={nodes.Object_212.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane105_217" position={[-2, 1, -5]}>
                <mesh
                  name="Object_214"
                  geometry={nodes.Object_214.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane106_218" position={[2, 1, -5]}>
                <mesh
                  name="Object_216"
                  geometry={nodes.Object_216.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane107_219" position={[1, -2, -5]}>
                <mesh
                  name="Object_218"
                  geometry={nodes.Object_218.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane108_220" position={[-2, -1, -5]}>
                <mesh
                  name="Object_220"
                  geometry={nodes.Object_220.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane109_221" position={[2, 3, -5]}>
                <mesh
                  name="Object_222"
                  geometry={nodes.Object_222.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane110_222" position={[1, 4, -5]}>
                <mesh
                  name="Object_224"
                  geometry={nodes.Object_224.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane111_223" position={[-1, 4, -5]}>
                <mesh
                  name="Object_226"
                  geometry={nodes.Object_226.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane112_224" position={[-3, 4, -5]}>
                <mesh
                  name="Object_228"
                  geometry={nodes.Object_228.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane113_225" position={[-4, 1, -5]}>
                <mesh
                  name="Object_230"
                  geometry={nodes.Object_230.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane114_226" position={[-4, 3, -5]}>
                <mesh
                  name="Object_232"
                  geometry={nodes.Object_232.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane115_227" position={[-4, -1, -5]}>
                <mesh
                  name="Object_234"
                  geometry={nodes.Object_234.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane116_228" position={[-4, -3, -5]}>
                <mesh
                  name="Object_236"
                  geometry={nodes.Object_236.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane117_229" position={[-3, -4, -5]}>
                <mesh
                  name="Object_238"
                  geometry={nodes.Object_238.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane118_230" position={[-1, -4, -5]}>
                <mesh
                  name="Object_240"
                  geometry={nodes.Object_240.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane119_231" position={[1, -4, -5]}>
                <mesh
                  name="Object_242"
                  geometry={nodes.Object_242.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane120_232" position={[3, -4, -5]}>
                <mesh
                  name="Object_244"
                  geometry={nodes.Object_244.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane121_233" position={[4, -3, -5]}>
                <mesh
                  name="Object_246"
                  geometry={nodes.Object_246.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane122_234" position={[4, -1, -5]}>
                <mesh
                  name="Object_248"
                  geometry={nodes.Object_248.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane123_235" position={[4, 1, -5]}>
                <mesh
                  name="Object_250"
                  geometry={nodes.Object_250.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane124_236" position={[4, 3, -5]}>
                <mesh
                  name="Object_252"
                  geometry={nodes.Object_252.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group
                name="Plane125_265"
                position={[0, -1, 5]}
                rotation={[0, 0, Math.PI]}
              >
                <mesh
                  name="Object_254"
                  geometry={nodes.Object_254.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane126_266" position={[0, 1, 5]}>
                <mesh
                  name="Object_256"
                  geometry={nodes.Object_256.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane127_267" position={[1, 2, 5]}>
                <mesh
                  name="Object_258"
                  geometry={nodes.Object_258.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane128_268" position={[-2, -1, 5]}>
                <mesh
                  name="Object_260"
                  geometry={nodes.Object_260.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane129_269" position={[1, -2, 5]}>
                <mesh
                  name="Object_262"
                  geometry={nodes.Object_262.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane130_270" position={[2, 1, 5]}>
                <mesh
                  name="Object_264"
                  geometry={nodes.Object_264.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane131_271" position={[-2, 1, 5]}>
                <mesh
                  name="Object_266"
                  geometry={nodes.Object_266.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane132_272" position={[-1, -2, 5]}>
                <mesh
                  name="Object_268"
                  geometry={nodes.Object_268.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane133_273" position={[2, -1, 5]}>
                <mesh
                  name="Object_270"
                  geometry={nodes.Object_270.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane134_274" position={[-2, 3, 5]}>
                <mesh
                  name="Object_272"
                  geometry={nodes.Object_272.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane135_275" position={[-1, 4, 5]}>
                <mesh
                  name="Object_274"
                  geometry={nodes.Object_274.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane136_276" position={[1, 4, 5]}>
                <mesh
                  name="Object_276"
                  geometry={nodes.Object_276.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane137_277" position={[3, 4, 5]}>
                <mesh
                  name="Object_278"
                  geometry={nodes.Object_278.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane138_278" position={[4, 1, 5]}>
                <mesh
                  name="Object_280"
                  geometry={nodes.Object_280.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane139_279" position={[4, 3, 5]}>
                <mesh
                  name="Object_282"
                  geometry={nodes.Object_282.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane140_280" position={[4, -1, 5]}>
                <mesh
                  name="Object_284"
                  geometry={nodes.Object_284.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane141_281" position={[4, -3, 5]}>
                <mesh
                  name="Object_286"
                  geometry={nodes.Object_286.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane142_282" position={[3, -4, 5]}>
                <mesh
                  name="Object_288"
                  geometry={nodes.Object_288.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane143_283" position={[1, -4, 5]}>
                <mesh
                  name="Object_290"
                  geometry={nodes.Object_290.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane144_284" position={[-1, -4, 5]}>
                <mesh
                  name="Object_292"
                  geometry={nodes.Object_292.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane145_285" position={[-3, -4, 5]}>
                <mesh
                  name="Object_294"
                  geometry={nodes.Object_294.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane146_286" position={[-4, -3, 5]}>
                <mesh
                  name="Object_296"
                  geometry={nodes.Object_296.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane147_287" position={[-4, -1, 5]}>
                <mesh
                  name="Object_298"
                  geometry={nodes.Object_298.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane148_288" position={[-4, 1, 5]}>
                <mesh
                  name="Object_300"
                  geometry={nodes.Object_300.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Plane149_289" position={[-4, 3, 5]}>
                <mesh
                  name="Object_302"
                  geometry={nodes.Object_302.geometry}
                  material={materials["Material.001"]}
                />
              </group>
              <group name="Sphere_318" scale={2.974}>
                <mesh
                  name="Object_304"
                  geometry={nodes.Object_304.geometry}
                  material={materials.material}
                />
              </group>
              <group name="Cube_319" scale={2.972}>
                <mesh
                  name="Object_306"
                  geometry={nodes.Object_306.geometry}
                  material={materials.material_2}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/glitch/glitch.glb");
