/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 spaceship.glb 
Author: cathole233 (https://sketchfab.com/cathole_1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bear-balloon-spaceship-f135368f5a234ce49b66d74273f751b6
Title: Bear Balloon Spaceship
*/

"use client"

import { useGLTF, useAnimations } from "@react-three/drei";
import { useRef } from "react";

export default function Spaceship(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/spaceship/spaceship.glb"
  );
  const { actions } = useAnimations(animations, group);

  return (
    <group scale={props.scale} renderOrder={props.renderOrder} ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="27d77af2da374929bd52c18939b03428fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="���_2"
                  position={[-0.192, 5.845, 0.644]}
                  rotation={[-0.032, 0, 0]}
                >
                  <group
                    name="������_8"
                    position={[-3.451, -0.808, 0.025]}
                    scale={0}
                  >
                    <group
                      name="modown_models_1"
                      position={[-3.643, 5.038, 0.694]}
                      rotation={[-0.032, 0, -0.443]}
                      scale={0}
                    >
                      <mesh
                        name="modown_models_1_lambert6_0"
                        geometry={nodes.modown_models_1_lambert6_0.geometry}
                        material={materials.lambert6}
                      />
                    </group>
                    <group
                      name="modown_models_4"
                      position={[-3.643, 5.038, 0.694]}
                      rotation={[-0.032, 0, -2.517]}
                      scale={0}
                    >
                      <mesh
                        name="modown_models_4_SIDAI_0"
                        geometry={nodes.modown_models_4_SIDAI_0.geometry}
                        material={materials.SIDAI}
                      />
                    </group>
                  </group>
                  <group
                    name="������_7"
                    position={[-3.829, -1.085, -0.246]}
                    scale={0}
                  >
                    <group
                      name="modown_models_1_2"
                      position={[-4.02, 4.753, 0.432]}
                      rotation={[-0.032, 0, -0.443]}
                      scale={0}
                    >
                      <mesh
                        name="modown_models_1_2_lambert13_0"
                        geometry={nodes.modown_models_1_2_lambert13_0.geometry}
                        material={materials.lambert13}
                      />
                    </group>
                    <group
                      name="modown_models_4_2"
                      position={[-4.02, 4.753, 0.432]}
                      rotation={[-0.032, 0, -2.517]}
                      scale={0}
                    >
                      <mesh
                        name="modown_models_4_2_SIDAI_0"
                        geometry={nodes.modown_models_4_2_SIDAI_0.geometry}
                        material={materials.SIDAI}
                      />
                    </group>
                  </group>
                  <group
                    name="������_6"
                    position={[0.25, -0.908, -0.845]}
                    scale={0}
                  >
                    <group
                      name="modown_models_1_3"
                      position={[0.058, 4.911, -0.172]}
                      rotation={[-0.032, 0, -0.443]}
                      scale={0}
                    >
                      <mesh
                        name="modown_models_1_3_lambert13_0"
                        geometry={nodes.modown_models_1_3_lambert13_0.geometry}
                        material={materials.lambert13}
                      />
                    </group>
                    <group
                      name="modown_models_4_3"
                      position={[0.058, 4.911, -0.172]}
                      rotation={[-0.032, 0, -2.517]}
                      scale={0}
                    >
                      <mesh
                        name="modown_models_4_3_SIDAI_0"
                        geometry={nodes.modown_models_4_3_SIDAI_0.geometry}
                        material={materials.SIDAI}
                      />
                    </group>
                  </group>
                  <group
                    name="������_5"
                    position={[1.605, 3.305, -2.114]}
                    rotation={[1.554, 0.031, -0.145]}
                    scale={0.05}
                  >
                    <group
                      name="modown_models_1_4"
                      position={[0.809, -0.482, -0.012]}
                      rotation={[0, 0, -0.443]}
                    >
                      <mesh
                        name="modown_models_1_4_lambert4_0"
                        geometry={nodes.modown_models_1_4_lambert4_0.geometry}
                        material={materials.lambert4}
                      />
                    </group>
                    <group
                      name="modown_models_4_4"
                      position={[1.134, -1.471, 0.034]}
                      rotation={[0, 0, -2.517]}
                    >
                      <mesh
                        name="modown_models_4_4_SIDAI_0"
                        geometry={nodes.modown_models_4_4_SIDAI_0.geometry}
                        material={materials.SIDAI}
                      />
                    </group>
                  </group>
                  <group name="������" position={[6.813, 7.401, 1.913]}>
                    <group
                      name="balloon_13"
                      position={[1.335, 2.126, -1.859]}
                      rotation={[0, 0, -0.333]}
                    >
                      <mesh
                        name="balloon_13_lambert14_0"
                        geometry={nodes.balloon_13_lambert14_0.geometry}
                        material={materials.lambert14}
                      />
                    </group>
                    <group
                      name="balloon_12"
                      position={[1.692, 0.177, -1.749]}
                      rotation={[-0.284, 0.248, -0.449]}
                    >
                      <mesh
                        name="balloon_12_lambert3_0"
                        geometry={nodes.balloon_12_lambert3_0.geometry}
                        material={materials.lambert3}
                      />
                    </group>
                    <group
                      name="balloon_11"
                      position={[1.615, -1.567, -2.845]}
                      rotation={[-1.138, -0.052, -0.2]}
                    >
                      <mesh
                        name="balloon_11_lambert13_0"
                        geometry={nodes.balloon_11_lambert13_0.geometry}
                        material={materials.lambert13}
                      />
                    </group>
                    <group
                      name="balloon_10"
                      position={[0.736, 1.133, 2.492]}
                      rotation={[0.188, -0.476, -0.27]}
                    >
                      <mesh
                        name="balloon_10_lambert4_0"
                        geometry={nodes.balloon_10_lambert4_0.geometry}
                        material={materials.lambert4}
                      />
                    </group>
                    <group
                      name="balloon_6"
                      position={[-0.771, -1.418, -1.996]}
                      rotation={[-0.787, 0, 0]}
                    >
                      <mesh
                        name="balloon_6_lambert4_0"
                        geometry={nodes.balloon_6_lambert4_0.geometry}
                        material={materials.lambert4}
                      />
                    </group>
                    <group
                      name="balloon_5"
                      position={[-0.099, -1.382, 1.517]}
                      rotation={[0.74, -0.226, -0.302]}
                    >
                      <mesh
                        name="balloon_5_lambert6_0"
                        geometry={nodes.balloon_5_lambert6_0.geometry}
                        material={materials.lambert6}
                      />
                    </group>
                    <group
                      name="balloon_4"
                      position={[-1.756, -0.44, 1.463]}
                      rotation={[0.441, -0.077, 0.162]}
                    >
                      <mesh
                        name="balloon_4_lambert14_0"
                        geometry={nodes.balloon_4_lambert14_0.geometry}
                        material={materials.lambert14}
                      />
                    </group>
                    <group
                      name="balloon_2"
                      position={[1.692, -0.314, 3.247]}
                      rotation={[0.244, -0.452, -0.8]}
                    >
                      <mesh
                        name="balloon_2_lambert13_0"
                        geometry={nodes.balloon_2_lambert13_0.geometry}
                        material={materials.lambert13}
                      />
                    </group>
                    <group
                      name="balloon_1"
                      position={[-0.099, -0.061, -1.065]}
                      rotation={[0, 0, -0.31]}
                    >
                      <mesh
                        name="balloon_1_lambert6_0"
                        geometry={nodes.balloon_1_lambert6_0.geometry}
                        material={materials.lambert6}
                      />
                    </group>
                    <group
                      name="balloon"
                      position={[-2.38, -0.548, -1.049]}
                      rotation={[-0.355, 0, 0.602]}
                    >
                      <mesh
                        name="balloon_lambert3_0"
                        geometry={nodes.balloon_lambert3_0.geometry}
                        material={materials.lambert3}
                      />
                    </group>
                  </group>
                  <group
                    name="������2"
                    position={[-1.172, 2.244, 0.79]}
                    rotation={[0, 0, 0.231]}
                  >
                    <group
                      name="balloon_9"
                      position={[-1.225, -0.792, -0.843]}
                      rotation={[0.174, 0.381, -0.391]}
                      scale={0.7}
                    >
                      <mesh
                        name="balloon_9_lambert2_0"
                        geometry={nodes.balloon_9_lambert2_0.geometry}
                        material={materials.lambert2}
                      />
                    </group>
                    <group
                      name="balloon_8"
                      position={[-0.383, 0.212, -0.08]}
                      rotation={[0, 0, -0.491]}
                      scale={0.8}
                    >
                      <mesh
                        name="balloon_8_lambert4_0"
                        geometry={nodes.balloon_8_lambert4_0.geometry}
                        material={materials.lambert4}
                      />
                    </group>
                  </group>
                  <group
                    name="������_3"
                    position={[1.724, 2.793, -2.044]}
                    rotation={[1.554, 0.009, 0.968]}
                    scale={0.9}
                  >
                    <group
                      name="modown_models_1_5"
                      position={[0.791, -0.525, -0.07]}
                      rotation={[0, 0, -0.443]}
                    >
                      <mesh
                        name="modown_models_1_5_lambert3_0"
                        geometry={nodes.modown_models_1_5_lambert3_0.geometry}
                        material={materials.lambert3}
                      />
                    </group>
                    <group
                      name="modown_models_4_5"
                      position={[1.116, -1.513, -0.024]}
                      rotation={[0, 0, -2.517]}
                    >
                      <mesh
                        name="modown_models_4_5_SIDAI_0"
                        geometry={nodes.modown_models_4_5_SIDAI_0.geometry}
                        material={materials.SIDAI}
                      />
                    </group>
                  </group>
                  <group
                    name="������_2"
                    position={[-0.219, -0.553, 1.288]}
                    rotation={[1.428, 0.06, 0.733]}
                    scale={0.193}
                  >
                    <group
                      name="modown_models_1_6"
                      position={[7.108, -0.381, -0.626]}
                      rotation={[0, 0, -0.443]}
                    >
                      <mesh
                        name="modown_models_1_6_lambert4_0"
                        geometry={nodes.modown_models_1_6_lambert4_0.geometry}
                        material={materials.lambert4}
                      />
                    </group>
                    <group
                      name="modown_models_4_6"
                      position={[0.002, -1.587, -0.449]}
                      rotation={[0, 0, -2.517]}
                    >
                      <mesh
                        name="modown_models_4_6_SIDAI_0"
                        geometry={nodes.modown_models_4_6_SIDAI_0.geometry}
                        material={materials.SIDAI}
                      />
                    </group>
                  </group>
                  <group
                    name="������_1_2"
                    position={[0.317, -1.054, 2.179]}
                    rotation={[1.428, 0.06, 0.187]}
                    scale={0.889}
                  >
                    <group
                      name="modown_models_1_7"
                      position={[7.108, -1.586, -0.626]}
                      rotation={[0, 0, -0.443]}
                    >
                      <mesh
                        name="modown_models_1_7_lambert2_0"
                        geometry={nodes.modown_models_1_7_lambert2_0.geometry}
                        material={materials.lambert2}
                      />
                    </group>
                    <group
                      name="modown_models_4_7"
                      position={[0.002, -2.792, -0.449]}
                      rotation={[0, 0, -2.517]}
                    >
                      <mesh
                        name="modown_models_4_7_SIDAI_0"
                        geometry={nodes.modown_models_4_7_SIDAI_0.geometry}
                        material={materials.SIDAI}
                      />
                    </group>
                  </group>
                  <group
                    name="���������"
                    position={[-1.446, -1.183, -0.585]}
                    rotation={[0.331, -1.216, 0.324]}
                    scale={0.06}
                  >
                    <mesh
                      name="���������_lambert9_0"
                      geometry={nodes["���������_lambert9_0"].geometry}
                      material={materials.lambert9}
                    />
                    <mesh
                      name="���������_lambert9_0_1"
                      geometry={nodes["���������_lambert9_0_1"].geometry}
                      material={materials.lambert9}
                    />
                    <mesh
                      name="���������_lambert9_0_2"
                      geometry={nodes["���������_lambert9_0_2"].geometry}
                      material={materials.lambert9}
                    />
                  </group>
                  <group name="���_2_1" position={[0.192, -5.845, -0.644]}>
                    <group
                      name="������_1"
                      position={[8.674, 5.681, 0.834]}
                      rotation={[1.015, 0, 0]}
                    >
                      <group name="scr_1" position={[-8.674, -5.681, -0.834]}>
                        <mesh
                          name="scr_1_lambert5_0"
                          geometry={nodes.scr_1_lambert5_0.geometry}
                          material={materials.lambert5}
                        />
                      </group>
                      <group name="scr_2" position={[-8.674, -5.681, -0.834]}>
                        <mesh
                          name="scr_2_lambert5_0"
                          geometry={nodes.scr_2_lambert5_0.geometry}
                          material={materials.lambert5}
                        />
                      </group>
                      <group name="scr_3" position={[-8.674, -5.681, -0.834]}>
                        <mesh
                          name="scr_3_lambert5_0"
                          geometry={nodes.scr_3_lambert5_0.geometry}
                          material={materials.lambert5}
                        />
                      </group>
                      <group name="scr_4" position={[-8.674, -5.681, -0.834]}>
                        <mesh
                          name="scr_4_lambert5_0"
                          geometry={nodes.scr_4_lambert5_0.geometry}
                          material={materials.lambert5}
                        />
                      </group>
                      <group name="scr_5" position={[-8.674, -5.681, -0.834]}>
                        <mesh
                          name="scr_5_lambert5_0"
                          geometry={nodes.scr_5_lambert5_0.geometry}
                          material={materials.lambert5}
                        />
                      </group>
                      <group name="scr_6" position={[-8.674, -5.681, -0.834]}>
                        <mesh
                          name="scr_6_lambert5_0"
                          geometry={nodes.scr_6_lambert5_0.geometry}
                          material={materials.lambert5}
                        />
                      </group>
                    </group>
                    <group
                      name="������_4"
                      position={[2.12, 3.853, -2.384]}
                      rotation={[-2.459, 0, 0]}
                    >
                      <group
                        name="pCylinder4"
                        position={[-2.12, -3.853, 2.384]}
                      >
                        <mesh
                          name="pCylinder4_lambert8_0"
                          geometry={nodes.pCylinder4_lambert8_0.geometry}
                          material={materials.lambert8}
                        />
                      </group>
                      <group
                        name="pCylinder5"
                        position={[-2.12, -3.853, 2.384]}
                      >
                        <mesh
                          name="pCylinder5_lambert8_0"
                          geometry={nodes.pCylinder5_lambert8_0.geometry}
                          material={materials.lambert8}
                        />
                      </group>
                    </group>
                    <group
                      name="���"
                      position={[-2.563, 5.736, -0.034]}
                      rotation={[-1.006, 0, 0]}
                    >
                      <group name="wheel" position={[2.563, -5.736, 0.034]}>
                        <mesh
                          name="wheel_lambert8_0"
                          geometry={nodes.wheel_lambert8_0.geometry}
                          material={materials.lambert8}
                        />
                      </group>
                      <group name="rail_1" position={[2.563, -5.736, 0.034]}>
                        <mesh
                          name="rail_1_lambert8_0"
                          geometry={nodes.rail_1_lambert8_0.geometry}
                          material={materials.lambert8}
                        />
                      </group>
                      <group name="rail_2" position={[2.563, -5.736, 0.034]}>
                        <mesh
                          name="rail_2_lambert8_0"
                          geometry={nodes.rail_2_lambert8_0.geometry}
                          material={materials.lambert8}
                        />
                      </group>
                      <group name="rail_3" position={[2.563, -5.736, 0.034]}>
                        <mesh
                          name="rail_3_lambert8_0"
                          geometry={nodes.rail_3_lambert8_0.geometry}
                          material={materials.lambert8}
                        />
                      </group>
                      <group name="rail_4" position={[2.563, -5.736, 0.034]}>
                        <mesh
                          name="rail_4_lambert8_0"
                          geometry={nodes.rail_4_lambert8_0.geometry}
                          material={materials.lambert8}
                        />
                      </group>
                      <group name="rail_5" position={[2.563, -5.736, 0.034]}>
                        <mesh
                          name="rail_5_lambert8_0"
                          geometry={nodes.rail_5_lambert8_0.geometry}
                          material={materials.lambert8}
                        />
                      </group>
                      <group name="rail_6" position={[2.563, -5.736, 0.034]}>
                        <mesh
                          name="rail_6_lambert8_0"
                          geometry={nodes.rail_6_lambert8_0.geometry}
                          material={materials.lambert8}
                        />
                      </group>
                      <group name="rail_7" position={[2.563, -5.736, 0.034]}>
                        <mesh
                          name="rail_7_lambert8_0"
                          geometry={nodes.rail_7_lambert8_0.geometry}
                          material={materials.lambert8}
                        />
                      </group>
                      <group name="rail_8" position={[2.563, -5.736, 0.034]}>
                        <mesh
                          name="rail_8_lambert8_0"
                          geometry={nodes.rail_8_lambert8_0.geometry}
                          material={materials.lambert8}
                        />
                      </group>
                      <group name="handle_1" position={[2.563, -5.736, 0.034]}>
                        <mesh
                          name="handle_1_lambert8_0"
                          geometry={nodes.handle_1_lambert8_0.geometry}
                          material={materials.lambert8}
                        />
                      </group>
                      <group name="handle_2" position={[2.563, -5.736, 0.034]}>
                        <mesh
                          name="handle_2_lambert8_0"
                          geometry={nodes.handle_2_lambert8_0.geometry}
                          material={materials.lambert8}
                        />
                      </group>
                      <group name="handle_3" position={[2.563, -5.736, 0.034]}>
                        <mesh
                          name="handle_3_lambert8_0"
                          geometry={nodes.handle_3_lambert8_0.geometry}
                          material={materials.lambert8}
                        />
                      </group>
                      <group name="handle_4" position={[2.563, -5.736, 0.034]}>
                        <mesh
                          name="handle_4_lambert8_0"
                          geometry={nodes.handle_4_lambert8_0.geometry}
                          material={materials.lambert8}
                        />
                      </group>
                      <group name="handle_5" position={[2.563, -5.736, 0.034]}>
                        <mesh
                          name="handle_5_lambert8_0"
                          geometry={nodes.handle_5_lambert8_0.geometry}
                          material={materials.lambert8}
                        />
                      </group>
                      <group name="handle_6" position={[2.563, -5.736, 0.034]}>
                        <mesh
                          name="handle_6_lambert8_0"
                          geometry={nodes.handle_6_lambert8_0.geometry}
                          material={materials.lambert8}
                        />
                      </group>
                      <group name="handle_7" position={[2.563, -5.736, 0.034]}>
                        <mesh
                          name="handle_7_lambert8_0"
                          geometry={nodes.handle_7_lambert8_0.geometry}
                          material={materials.lambert8}
                        />
                      </group>
                      <group name="handle_8" position={[2.563, -5.736, 0.034]}>
                        <mesh
                          name="handle_8_lambert8_0"
                          geometry={nodes.handle_8_lambert8_0.geometry}
                          material={materials.lambert8}
                        />
                      </group>
                    </group>
                    <group name="cyl_2">
                      <mesh
                        name="cyl_2_lambert5_0"
                        geometry={nodes.cyl_2_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="cyl_4">
                      <mesh
                        name="cyl_4_lambert5_0"
                        geometry={nodes.cyl_4_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="cover">
                      <mesh
                        name="cover_lambert5_0"
                        geometry={nodes.cover_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="min_1">
                      <mesh
                        name="min_1_lambert5_0"
                        geometry={nodes.min_1_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="min_2">
                      <mesh
                        name="min_2_lambert5_0"
                        geometry={nodes.min_2_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube96">
                      <mesh
                        name="pCube96_lambert5_0"
                        geometry={nodes.pCube96_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube95">
                      <mesh
                        name="pCube95_lambert5_0"
                        geometry={nodes.pCube95_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube94">
                      <mesh
                        name="pCube94_lambert5_0"
                        geometry={nodes.pCube94_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube93">
                      <mesh
                        name="pCube93_lambert5_0"
                        geometry={nodes.pCube93_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube92">
                      <mesh
                        name="pCube92_lambert5_0"
                        geometry={nodes.pCube92_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube91">
                      <mesh
                        name="pCube91_lambert5_0"
                        geometry={nodes.pCube91_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube90">
                      <mesh
                        name="pCube90_lambert5_0"
                        geometry={nodes.pCube90_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube89">
                      <mesh
                        name="pCube89_lambert5_0"
                        geometry={nodes.pCube89_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube88">
                      <mesh
                        name="pCube88_lambert5_0"
                        geometry={nodes.pCube88_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="polySurface17">
                      <mesh
                        name="polySurface17_MUTOU_0"
                        geometry={nodes.polySurface17_MUTOU_0.geometry}
                        material={materials.MUTOU}
                      />
                    </group>
                    <group name="polySurface18">
                      <mesh
                        name="polySurface18_MUTOU_0"
                        geometry={nodes.polySurface18_MUTOU_0.geometry}
                        material={materials.MUTOU}
                      />
                    </group>
                    <group name="polySurface19">
                      <mesh
                        name="polySurface19_lambert5_0"
                        geometry={nodes.polySurface19_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="polySurface20">
                      <mesh
                        name="polySurface20_MUTOU_0"
                        geometry={nodes.polySurface20_MUTOU_0.geometry}
                        material={materials.MUTOU}
                      />
                    </group>
                    <group name="polySurface21">
                      <mesh
                        name="polySurface21_MUTOU_0"
                        geometry={nodes.polySurface21_MUTOU_0.geometry}
                        material={materials.MUTOU}
                      />
                    </group>
                    <group name="polySurface22">
                      <mesh
                        name="polySurface22_lambert5_0"
                        geometry={nodes.polySurface22_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="polySurface23">
                      <mesh
                        name="polySurface23_MUTOU_0"
                        geometry={nodes.polySurface23_MUTOU_0.geometry}
                        material={materials.MUTOU}
                      />
                    </group>
                    <group name="polySurface24">
                      <mesh
                        name="polySurface24_MUTOU_0"
                        geometry={nodes.polySurface24_MUTOU_0.geometry}
                        material={materials.MUTOU}
                      />
                    </group>
                    <group name="polySurface4">
                      <mesh
                        name="polySurface4_MUTOU_0"
                        geometry={nodes.polySurface4_MUTOU_0.geometry}
                        material={materials.MUTOU}
                      />
                    </group>
                    <group name="polySurface5">
                      <mesh
                        name="polySurface5_MUTOU_0"
                        geometry={nodes.polySurface5_MUTOU_0.geometry}
                        material={materials.MUTOU}
                      />
                    </group>
                    <group name="polySurface6">
                      <mesh
                        name="polySurface6_MUTOU_0"
                        geometry={nodes.polySurface6_MUTOU_0.geometry}
                        material={materials.MUTOU}
                      />
                    </group>
                    <group name="polySurface7">
                      <mesh
                        name="polySurface7_MUTOU_0"
                        geometry={nodes.polySurface7_MUTOU_0.geometry}
                        material={materials.MUTOU}
                      />
                    </group>
                    <group name="polySurface8">
                      <mesh
                        name="polySurface8_MUTOU_0"
                        geometry={nodes.polySurface8_MUTOU_0.geometry}
                        material={materials.MUTOU}
                      />
                    </group>
                    <group name="polySurface9">
                      <mesh
                        name="polySurface9_MUTOU_0"
                        geometry={nodes.polySurface9_MUTOU_0.geometry}
                        material={materials.MUTOU}
                      />
                    </group>
                    <group name="polySurface10">
                      <mesh
                        name="polySurface10_MUTOU_0"
                        geometry={nodes.polySurface10_MUTOU_0.geometry}
                        material={materials.MUTOU}
                      />
                    </group>
                    <group name="polySurface11">
                      <mesh
                        name="polySurface11_MUTOU_0"
                        geometry={nodes.polySurface11_MUTOU_0.geometry}
                        material={materials.MUTOU}
                      />
                    </group>
                    <group name="polySurface12">
                      <mesh
                        name="polySurface12_MUTOU_0"
                        geometry={nodes.polySurface12_MUTOU_0.geometry}
                        material={materials.MUTOU}
                      />
                    </group>
                    <group name="polySurface13">
                      <mesh
                        name="polySurface13_MUTOU_0"
                        geometry={nodes.polySurface13_MUTOU_0.geometry}
                        material={materials.MUTOU}
                      />
                    </group>
                    <group name="polySurface36">
                      <mesh
                        name="polySurface36_MU_0"
                        geometry={nodes.polySurface36_MU_0.geometry}
                        material={materials.material}
                      />
                    </group>
                    <group name="polySurface39">
                      <mesh
                        name="polySurface39_MU_0"
                        geometry={nodes.polySurface39_MU_0.geometry}
                        material={materials.material}
                      />
                    </group>
                    <group name="pCube80" position={[0, 0, -0.076]}>
                      <mesh
                        name="pCube80_lambert5_0"
                        geometry={nodes.pCube80_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube79">
                      <mesh
                        name="pCube79_lambert5_0"
                        geometry={nodes.pCube79_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube78">
                      <mesh
                        name="pCube78_lambert5_0"
                        geometry={nodes.pCube78_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube77">
                      <mesh
                        name="pCube77_lambert5_0"
                        geometry={nodes.pCube77_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube76">
                      <mesh
                        name="pCube76_lambert5_0"
                        geometry={nodes.pCube76_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube75">
                      <mesh
                        name="pCube75_lambert5_0"
                        geometry={nodes.pCube75_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube74">
                      <mesh
                        name="pCube74_lambert5_0"
                        geometry={nodes.pCube74_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube73">
                      <mesh
                        name="pCube73_lambert5_0"
                        geometry={nodes.pCube73_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube72">
                      <mesh
                        name="pCube72_MUTOU_0"
                        geometry={nodes.pCube72_MUTOU_0.geometry}
                        material={materials.MUTOU}
                      />
                    </group>
                    <group name="pCube71">
                      <mesh
                        name="pCube71_MUTOU_0"
                        geometry={nodes.pCube71_MUTOU_0.geometry}
                        material={materials.MUTOU}
                      />
                    </group>
                    <group name="pCube70">
                      <mesh
                        name="pCube70_lambert5_0"
                        geometry={nodes.pCube70_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube69">
                      <mesh
                        name="pCube69_lambert5_0"
                        geometry={nodes.pCube69_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube68">
                      <mesh
                        name="pCube68_lambert5_0"
                        geometry={nodes.pCube68_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube67">
                      <mesh
                        name="pCube67_lambert5_0"
                        geometry={nodes.pCube67_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube64">
                      <mesh
                        name="pCube64_lambert5_0"
                        geometry={nodes.pCube64_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube62">
                      <mesh
                        name="pCube62_lambert5_0"
                        geometry={nodes.pCube62_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube61">
                      <mesh
                        name="pCube61_lambert5_0"
                        geometry={nodes.pCube61_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube60">
                      <mesh
                        name="pCube60_lambert5_0"
                        geometry={nodes.pCube60_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube59">
                      <mesh
                        name="pCube59_lambert5_0"
                        geometry={nodes.pCube59_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube57">
                      <mesh
                        name="pCube57_lambert5_0"
                        geometry={nodes.pCube57_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube56">
                      <mesh
                        name="pCube56_lambert5_0"
                        geometry={nodes.pCube56_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube55">
                      <mesh
                        name="pCube55_lambert5_0"
                        geometry={nodes.pCube55_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube54">
                      <mesh
                        name="pCube54_lambert5_0"
                        geometry={nodes.pCube54_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube53">
                      <mesh
                        name="pCube53_lambert5_0"
                        geometry={nodes.pCube53_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube52">
                      <mesh
                        name="pCube52_lambert5_0"
                        geometry={nodes.pCube52_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube50">
                      <mesh
                        name="pCube50_lambert5_0"
                        geometry={nodes.pCube50_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube47">
                      <mesh
                        name="pCube47_MUTOU_0"
                        geometry={nodes.pCube47_MUTOU_0.geometry}
                        material={materials.MUTOU}
                      />
                    </group>
                    <group name="pCube46">
                      <mesh
                        name="pCube46_lambert5_0"
                        geometry={nodes.pCube46_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube45">
                      <mesh
                        name="pCube45_lambert5_0"
                        geometry={nodes.pCube45_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="polySurface1">
                      <mesh
                        name="polySurface1_MU_0"
                        geometry={nodes.polySurface1_MU_0.geometry}
                        material={materials.material}
                      />
                    </group>
                    <group name="polySurface2">
                      <mesh
                        name="polySurface2_MU_0"
                        geometry={nodes.polySurface2_MU_0.geometry}
                        material={materials.material}
                      />
                    </group>
                    <group name="pCube43">
                      <mesh
                        name="pCube43_lambert5_0"
                        geometry={nodes.pCube43_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube41">
                      <mesh
                        name="pCube41_MUTOU_0"
                        geometry={nodes.pCube41_MUTOU_0.geometry}
                        material={materials.MUTOU}
                      />
                    </group>
                    <group name="pCube39">
                      <mesh
                        name="pCube39_lambert5_0"
                        geometry={nodes.pCube39_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube36">
                      <mesh
                        name="pCube36_lambert5_0"
                        geometry={nodes.pCube36_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube34">
                      <mesh
                        name="pCube34_lambert5_0"
                        geometry={nodes.pCube34_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube29">
                      <mesh
                        name="pCube29_lambert5_0"
                        geometry={nodes.pCube29_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube28">
                      <mesh
                        name="pCube28_lambert5_0"
                        geometry={nodes.pCube28_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube27">
                      <mesh
                        name="pCube27_lambert5_0"
                        geometry={nodes.pCube27_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube26">
                      <mesh
                        name="pCube26_lambert5_0"
                        geometry={nodes.pCube26_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube25">
                      <mesh
                        name="pCube25_lambert5_0"
                        geometry={nodes.pCube25_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube20">
                      <mesh
                        name="pCube20_lambert5_0"
                        geometry={nodes.pCube20_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube17">
                      <mesh
                        name="pCube17_lambert5_0"
                        geometry={nodes.pCube17_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube16">
                      <mesh
                        name="pCube16_lambert5_0"
                        geometry={nodes.pCube16_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube15">
                      <mesh
                        name="pCube15_lambert5_0"
                        geometry={nodes.pCube15_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube14">
                      <mesh
                        name="pCube14_lambert5_0"
                        geometry={nodes.pCube14_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube13" position={[0, 0, -0.119]}>
                      <mesh
                        name="pCube13_lambert5_0"
                        geometry={nodes.pCube13_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube8">
                      <mesh
                        name="pCube8_lambert5_0"
                        geometry={nodes.pCube8_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube6">
                      <mesh
                        name="pCube6_lambert5_0"
                        geometry={nodes.pCube6_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube4">
                      <mesh
                        name="pCube4_lambert5_0"
                        geometry={nodes.pCube4_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube2">
                      <mesh
                        name="pCube2_lambert5_0"
                        geometry={nodes.pCube2_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCube1">
                      <mesh
                        name="pCube1_lambert5_0"
                        geometry={nodes.pCube1_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="pCylinder3">
                      <mesh
                        name="pCylinder3_lambert8_0"
                        geometry={nodes.pCylinder3_lambert8_0.geometry}
                        material={materials.lambert8}
                      />
                    </group>
                    <group name="pCube15_2">
                      <mesh
                        name="pCube15_2_lambert8_0"
                        geometry={nodes.pCube15_2_lambert8_0.geometry}
                        material={materials.lambert8}
                      />
                    </group>
                    <group name="pCylinder6">
                      <mesh
                        name="pCylinder6_lambert8_0"
                        geometry={nodes.pCylinder6_lambert8_0.geometry}
                        material={materials.lambert8}
                      />
                    </group>
                    <group name="pCube16_2">
                      <mesh
                        name="pCube16_2_lambert8_0"
                        geometry={nodes.pCube16_2_lambert8_0.geometry}
                        material={materials.lambert8}
                      />
                    </group>
                    <group name="pad_handle">
                      <mesh
                        name="pad_handle_lambert8_0"
                        geometry={nodes.pad_handle_lambert8_0.geometry}
                        material={materials.lambert8}
                      />
                    </group>
                    <group name="paddle">
                      <mesh
                        name="paddle_lambert17_0"
                        geometry={nodes.paddle_lambert17_0.geometry}
                        material={materials.lambert17}
                      />
                    </group>
                    <group name="pad_stand">
                      <mesh
                        name="pad_stand_lambert5_0"
                        geometry={nodes.pad_stand_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="cyl_1">
                      <mesh
                        name="cyl_1_lambert5_0"
                        geometry={nodes.cyl_1_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="cyl_2_2">
                      <mesh
                        name="cyl_2_2_lambert5_0"
                        geometry={nodes.cyl_2_2_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="chair">
                      <mesh
                        name="chair_lambert5_0"
                        geometry={nodes.chair_lambert5_0.geometry}
                        material={materials.lambert5}
                      />
                    </group>
                    <group name="sphere">
                      <mesh
                        name="sphere_lambert8_0"
                        geometry={nodes.sphere_lambert8_0.geometry}
                        material={materials.lambert8}
                      />
                    </group>
                    <group name="stand">
                      <mesh
                        name="stand_lambert8_0"
                        geometry={nodes.stand_lambert8_0.geometry}
                        material={materials.lambert8}
                      />
                    </group>
                    <group name="boat1">
                      <mesh
                        name="boat1_lambert8_0"
                        geometry={nodes.boat1_lambert8_0.geometry}
                        material={materials.lambert8}
                      />
                    </group>
                  </group>
                  <group
                    name="���_3"
                    position={[-1.601, 0.296, -1.854]}
                    rotation={[-3.114, -0.774, -3.112]}
                    scale={0.03}
                  >
                    <group
                      name="������_9"
                      position={[11.688, -20.411, -8.692]}
                      rotation={[-2.72, 0.041, 0.445]}
                    >
                      <mesh
                        name="������_XIONG_0"
                        geometry={nodes["������_XIONG_0"].geometry}
                        material={materials.XIONG}
                      />
                    </group>
                    <group
                      name="������_10"
                      position={[-10.409, -25.908, -13.843]}
                      rotation={[0.641, 1.089, -2.887]}
                      scale={33.333}
                    >
                      <mesh
                        name="������_XIONG_0_1"
                        geometry={nodes["������_XIONG_0_1"].geometry}
                        material={materials.XIONG}
                      />
                    </group>
                    <group
                      name="������_11"
                      position={[-10.332, -36.185, 0]}
                      rotation={[-0.244, -0.303, -0.212]}
                    >
                      <mesh
                        name="������_XIONG_0_2"
                        geometry={nodes["������_XIONG_0_2"].geometry}
                        material={materials.XIONG}
                      />
                    </group>
                    <group
                      name="������_12"
                      position={[8.156, -37.321, -1.773]}
                      rotation={[2.944, 0.585, -2.875]}
                      scale={33.333}
                    >
                      <mesh
                        name="������_XIONG_0_3"
                        geometry={nodes["������_XIONG_0_3"].geometry}
                        material={materials.XIONG}
                      />
                    </group>
                    <group
                      name="������_13"
                      position={[-0.288, -27.597, -0.544]}
                      rotation={[-0.004, -0.272, -0.006]}
                      scale={1.056}
                    >
                      <group
                        name="���������������C4D������������"
                        position={[1.008, 3.964, 8.339]}
                        rotation={[2.841, -0.01, -3.124]}
                        scale={1.667}
                      >
                        <mesh
                          name="���������������C4D������������_lambert11_0"
                          geometry={
                            nodes["���������������C4D������������_lambert11_0"]
                              .geometry
                          }
                          material={materials.lambert11}
                        />
                      </group>
                      <mesh
                        name="������_XIONG_0_4"
                        geometry={nodes["������_XIONG_0_4"].geometry}
                        material={materials.XIONG}
                      />
                    </group>
                    <group
                      name="���_1"
                      position={[0.57, -2.493, -5.523]}
                      rotation={[0.133, -0.734, -0.134]}
                    >
                      <group name="������_14">
                        <mesh
                          name="������_XIONG_0_5"
                          geometry={nodes["������_XIONG_0_5"].geometry}
                          material={materials.XIONG}
                        />
                      </group>
                      <group
                        name="������_15"
                        position={[14.492, 16.609, -20.523]}
                        rotation={[-3.132, 0.774, -3.127]}
                        scale={33.333}
                      >
                        <mesh
                          name="������_XIONG_0_6"
                          geometry={nodes["������_XIONG_0_6"].geometry}
                          material={materials.XIONG}
                        />
                      </group>
                      <group name="Volume3_copy003">
                        <mesh
                          name="Volume3_copy003_XIONG_0"
                          geometry={nodes.Volume3_copy003_XIONG_0.geometry}
                          material={materials.XIONG}
                        />
                      </group>
                      <group name="Volume44_copy000">
                        <mesh
                          name="Volume44_copy000_XIONG_0"
                          geometry={nodes.Volume44_copy000_XIONG_0.geometry}
                          material={materials.XIONG}
                        />
                      </group>
                      <mesh
                        name="���_XIONG_0"
                        geometry={nodes["���_XIONG_0"].geometry}
                        material={materials.XIONG}
                      />
                    </group>
                  </group>
                </group>
                <group
                  name="������_16"
                  position={[12.209, -0.773, -0.753]}
                  scale={0.3}
                >
                  <group name="cyl_1_2" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="cyl_1_2_lambert8_0"
                      geometry={nodes.cyl_1_2_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="cyl_2_3" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="cyl_2_3_lambert8_0"
                      geometry={nodes.cyl_2_3_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="cyl_3" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="cyl_3_lambert8_0"
                      geometry={nodes.cyl_3_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="cyl_4_2" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="cyl_4_2_lambert8_0"
                      geometry={nodes.cyl_4_2_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="scr_1_2" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="scr_1_2_lambert8_0"
                      geometry={nodes.scr_1_2_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="scr_2_2" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="scr_2_2_lambert8_0"
                      geometry={nodes.scr_2_2_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="scr_3_2" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="scr_3_2_lambert8_0"
                      geometry={nodes.scr_3_2_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="scr_4_2" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="scr_4_2_lambert8_0"
                      geometry={nodes.scr_4_2_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="scr_5_2" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="scr_5_2_lambert8_0"
                      geometry={nodes.scr_5_2_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="scr_6_2" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="scr_6_2_lambert8_0"
                      geometry={nodes.scr_6_2_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="cover_2" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="cover_2_lambert8_0"
                      geometry={nodes.cover_2_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="polySurface48" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="polySurface48_lambert8_0"
                      geometry={nodes.polySurface48_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="polySurface49" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="polySurface49_lambert8_0"
                      geometry={nodes.polySurface49_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="polySurface50" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="polySurface50_lambert8_0"
                      geometry={nodes.polySurface50_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="polySurface51" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="polySurface51_lambert8_0"
                      geometry={nodes.polySurface51_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="polySurface56" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="polySurface56_lambert8_0"
                      geometry={nodes.polySurface56_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="polySurface57" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="polySurface57_lambert8_0"
                      geometry={nodes.polySurface57_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="polySurface58" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="polySurface58_lambert8_0"
                      geometry={nodes.polySurface58_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="wing_1" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="wing_1_lambert8_0"
                      geometry={nodes.wing_1_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="wing_2" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="wing_2_lambert8_0"
                      geometry={nodes.wing_2_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="wing_3" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="wing_3_lambert8_0"
                      geometry={nodes.wing_3_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="pCylinder39" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="pCylinder39_lambert8_0"
                      geometry={nodes.pCylinder39_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="pCylinder40" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="pCylinder40_lambert8_0"
                      geometry={nodes.pCylinder40_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="pCylinder37" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="pCylinder37_lambert8_0"
                      geometry={nodes.pCylinder37_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="pCylinder38" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="pCylinder38_lambert8_0"
                      geometry={nodes.pCylinder38_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="polySurface171" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="polySurface171_lambert8_0"
                      geometry={nodes.polySurface171_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="polySurface172" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="polySurface172_lambert8_0"
                      geometry={nodes.polySurface172_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="polySurface78" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="polySurface78_lambert8_0"
                      geometry={nodes.polySurface78_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="polySurface77" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="polySurface77_lambert8_0"
                      geometry={nodes.polySurface77_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="polySurface76" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="polySurface76_lambert8_0"
                      geometry={nodes.polySurface76_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="polySurface162" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="polySurface162_lambert8_0"
                      geometry={nodes.polySurface162_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="polySurface161" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="polySurface161_lambert8_0"
                      geometry={nodes.polySurface161_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="polySurface163" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="polySurface163_lambert8_0"
                      geometry={nodes.polySurface163_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="polySurface164" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="polySurface164_lambert8_0"
                      geometry={nodes.polySurface164_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="polySurface165" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="polySurface165_lambert8_0"
                      geometry={nodes.polySurface165_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="polySurface159" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="polySurface159_lambert8_0"
                      geometry={nodes.polySurface159_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="polySurface160" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="polySurface160_lambert8_0"
                      geometry={nodes.polySurface160_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="polySurface54" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="polySurface54_lambert8_0"
                      geometry={nodes.polySurface54_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="polySurface53" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="polySurface53_lambert8_0"
                      geometry={nodes.polySurface53_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="polySurface52" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="polySurface52_lambert8_0"
                      geometry={nodes.polySurface52_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="polySurface86" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="polySurface86_lambert8_0"
                      geometry={nodes.polySurface86_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="polySurface85" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="polySurface85_lambert8_0"
                      geometry={nodes.polySurface85_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="cab_1" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="cab_1_lambert8_0"
                      geometry={nodes.cab_1_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="cab_2" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="cab_2_lambert8_0"
                      geometry={nodes.cab_2_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="cab_3" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="cab_3_lambert8_0"
                      geometry={nodes.cab_3_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="cab_4" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="cab_4_lambert8_0"
                      geometry={nodes.cab_4_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="cab_5" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="cab_5_lambert8_0"
                      geometry={nodes.cab_5_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="cab_6" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="cab_6_lambert8_0"
                      geometry={nodes.cab_6_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="cab_7" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="cab_7_lambert8_0"
                      geometry={nodes.cab_7_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="cab_8" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="cab_8_lambert8_0"
                      geometry={nodes.cab_8_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="cab_9" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="cab_9_lambert8_0"
                      geometry={nodes.cab_9_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="cab_10" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="cab_10_lambert8_0"
                      geometry={nodes.cab_10_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="baloon_body" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="baloon_body_FEICHUAN_0"
                      geometry={nodes.baloon_body_FEICHUAN_0.geometry}
                      material={materials.FEICHUAN}
                    />
                  </group>
                  <group name="polySurface145" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="polySurface145_lambert8_0"
                      geometry={nodes.polySurface145_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="polySurface144" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="polySurface144_lambert8_0"
                      geometry={nodes.polySurface144_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="polySurface147" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="polySurface147_lambert8_0"
                      geometry={nodes.polySurface147_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                  <group name="polySurface146" position={[-30.712, -17.183, 0]}>
                    <mesh
                      name="polySurface146_lambert8_0"
                      geometry={nodes.polySurface146_lambert8_0.geometry}
                      material={materials.lambert8}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/spaceship/spaceship.glb");
